
import logging
from typing import List, Tuple, Optional

from cineengine.config import Config
from cineengine.subtitles.subtitle import Subtitle, SubtitleManager
from cineengine.subtitles.animation import SubtitleAnimation
from cineengine.subtitles.typography import TextRenderer

logger = logging.getLogger(__name__)

class Subtitles:
    """
    Manages subtitle creation, animation, and rendering within CineEngine.
    """
    def __init__(self, config: Config, ctx: Optional[moderngl.Context] = None):
        """
        Initializes the Subtitles module.

        Args:
            config (Config): The CineEngine configuration object.
            ctx (moderngl.Context, optional): The ModernGL context. Required for text rendering.
        """
        self.config = config
        self.ctx = ctx
        self.manager = SubtitleManager(config)
        self.text_renderer: Optional[TextRenderer] = None

        if self.ctx is None:
            logger.warning("ModernGL context not provided to Subtitles module. Text rendering will not be initialized.")
        else:
            self.text_renderer = TextRenderer(self.ctx, self.config.RESOLUTION)
            logger.info("Subtitles module initialized with ModernGL context.")

    def add(self, text: str, start_time: float, end_time: float, animation_type: Optional[str] = None) -> None:
        """
        Adds a subtitle to the timeline with optional animation.

        Args:
            text (str): The text content of the subtitle.
            start_time (float): The start time of the subtitle in seconds.
            end_time (float): The end time of the subtitle in seconds.
            animation_type (str, optional): Type of animation to apply (e.g., 'fade_in_out', 'slide_in_from_bottom').
        """
        self.manager.add_subtitle(text, start_time, end_time, animation_type=animation_type)

    def get_rendered_subtitles(self, current_time: float) -> List[Tuple[moderngl.Texture, Tuple[float, float], float]]:
        """
        Gets currently active subtitles and renders them to textures, applying animations.

        Args:
            current_time (float): The current time in seconds.

        Returns:
            List[Tuple[moderngl.Texture, Tuple[float, float], float]]: A list of tuples, each containing
            (rendered_text_texture, (normalized_x, normalized_y_position), alpha).
        """
        if self.text_renderer is None:
            logger.warning("TextRenderer not initialized. Cannot render subtitles.")
            return []

        rendered_subtitles = []
        active_subs = self.manager.get_active_subtitles(current_time)

        for sub in active_subs:
            # Calculate time within subtitle's active duration
            t_local = current_time - sub.start_time
            sub_duration = sub.end_time - sub.start_time

            alpha = 1.0
            y_offset = 0.0 # Normalized offset from original position

            if sub.animation_type:
                try:
                    anim_func = SubtitleAnimation.get_animation_function(sub.animation_type)
                    if sub.animation_type == 'fade_in_out':
                        alpha = anim_func(t_local, sub_duration)
                    elif sub.animation_type == 'slide_in_from_bottom':
                        y_offset = anim_func(t_local, sub_duration)
                        alpha = SubtitleAnimation.fade_in_out(t_local, sub_duration) # Combine with fade for slide
                    # Add more animation types here
                except ValueError as e:
                    logger.error(f"Error applying animation '{sub.animation_type}': {e}")

            # Apply alpha to color
            animated_color = (sub.color[0], sub.color[1], sub.color[2], sub.color[3] * alpha)

            # Render text to texture
            text_texture = self.text_renderer.render_text_to_texture(
                sub.text,
                self.config.SUBTITLE_FONT, # Assuming this is a path to a .ttf file
                sub.font_size,
                animated_color
            )

            # Calculate final position (normalized)
            final_pos_y = sub.position[1] + y_offset
            rendered_subtitles.append((text_texture, (sub.position[0], final_pos_y), alpha))

        return rendered_subtitles

    def clear_all_subtitles(self) -> None:
        """
        Clears all subtitles from the manager.
        """
        self.manager.clear_subtitles()

    def release(self):
        """
        Releases resources held by the subtitle module.
        """
        # Textures generated by render_text_to_texture need to be released after use
        # This method would typically be called when the entire CineEngine is shutting down.
        # Individual textures are managed by the renderer during frame generation.
        logger.info("Subtitles module resources released.")

if __name__ == "__main__":
    print("Subtitles module requires a ModernGL context for full functionality. This is a placeholder example.")
    print("To test, you would typically run this within a rendering loop:")
    print("    from cineengine.config import Config")
    print("    config = Config()")
    print("    # ctx = moderngl.create_context(standalone=True) # For testing without a window")
    print("    # subtitles_module = Subtitles(config, ctx)")
    print("    # subtitles_module.add(\"Hello World!\", 0.0, 2.0, animation_type=\"fade_in_out\")")
    print("    # subtitles_module.add(\"Slide In!\", 1.0, 3.0, animation_type=\"slide_in_from_bottom\")")
    print("    # for t in np.arange(0, 3.5, 0.1):")
    print("    #     active_renders = subtitles_module.get_rendered_subtitles(t)")
    print("    #     for texture, pos, alpha in active_renders:")
    print("    #         print(f'Time: {t:.1f}s, Text Texture: {texture}, Position: {pos}, Alpha: {alpha:.2f}')")
    print("    #         texture.release() # Release texture after use")
    print("    # ctx.release()")
